--------------------------------------------------------
--  DDL for Table ALLAS_ADATOK
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."ALLAS_ADATOK" 
   (	"ID" NUMBER(5,0), 
	"HELYSZIN" VARCHAR2(50 BYTE), 
	"MUSZAK" VARCHAR2(10 BYTE), 
	"LEIRAS" VARCHAR2(50 BYTE), 
	"TIPUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ALLAS_LEHETOSEG
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."ALLAS_LEHETOSEG" 
   (	"ID" NUMBER(5,0), 
	"MK_ADOSZAM" VARCHAR2(13 BYTE), 
	"MC_ADOSZAM" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ISKOLAI_VEGZETTSEGEK
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."ISKOLAI_VEGZETTSEGEK" 
   (	"CV_ID" NUMBER(5,0), 
	"ISKOLAI_VEGZETTSEG" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KOZVETITESEK
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."KOZVETITESEK" 
   (	"ADOSZAM" VARCHAR2(13 BYTE), 
	"SZEMELY_SZAM" VARCHAR2(8 BYTE), 
	"KOZ_KOD" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KOZVETITO
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."KOZVETITO" 
   (	"ADOSZAM" VARCHAR2(13 BYTE), 
	"MEGNEVEZES" VARCHAR2(50 BYTE), 
	"HELYSZIN" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUNKALTATO_CEG
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."MUNKALTATO_CEG" 
   (	"ADOSZAM" VARCHAR2(13 BYTE), 
	"NEV" VARCHAR2(50 BYTE), 
	"TELEPHELY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUNKALTATO_CEG_KATEGORIAK
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" 
   (	"ID" NUMBER(5,0), 
	"ADOSZAM" VARCHAR2(13 BYTE), 
	"MEGNEVEZES" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUNKAVALLALO
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."MUNKAVALLALO" 
   (	"SZEMELY_SZAM" VARCHAR2(8 BYTE), 
	"NEM" VARCHAR2(10 BYTE), 
	"SZUL_DATUM" DATE DEFAULT NULL, 
	"LAKCIM" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"NEV" VARCHAR2(30 BYTE), 
	"KAT_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUNKAVALLALO_KATEGORIAK
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."MUNKAVALLALO_KATEGORIAK" 
   (	"ID" NUMBER(5,0), 
	"MEGNEVEZES" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ONELETRAJZ
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."ONELETRAJZ" 
   (	"ID" NUMBER(5,0), 
	"REFERENCIA" VARCHAR2(50 BYTE), 
	"SZEMELY_SZAM" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGISTER
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."REGISTER" 
   (	"USERNAME" VARCHAR2(60 BYTE), 
	"REG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SZAKMAI_TAPASZTALAT
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."SZAKMAI_TAPASZTALAT" 
   (	"CV_ID" NUMBER(5,0), 
	"SZAKMAI_TAPASZTALAT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAPASZTALAT
--------------------------------------------------------

  CREATE TABLE "SZABARNA"."TAPASZTALAT" 
   (	"ID" NUMBER(5,0), 
	"SZEMELY_SZAM" VARCHAR2(11 BYTE), 
	"MEGNEVEZES" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLAS_ADATOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."ALLAS_ADATOK_PK" ON "SZABARNA"."ALLAS_ADATOK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLAS_LEHETOSEG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."ALLAS_LEHETOSEG_UK1" ON "SZABARNA"."ALLAS_LEHETOSEG" ("MK_ADOSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010069
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010069" ON "SZABARNA"."ALLAS_LEHETOSEG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALLAS_LEHETOSEG_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."ALLAS_LEHETOSEG_UK2" ON "SZABARNA"."ALLAS_LEHETOSEG" ("MC_ADOSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010072
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010072" ON "SZABARNA"."ISKOLAI_VEGZETTSEGEK" ("CV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010076
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010076" ON "SZABARNA"."KOZVETITESEK" ("ADOSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KOZVETITESEK_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."KOZVETITESEK_UK1" ON "SZABARNA"."KOZVETITESEK" ("SZEMELY_SZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010080
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010080" ON "SZABARNA"."KOZVETITO" ("ADOSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010084
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010084" ON "SZABARNA"."MUNKALTATO_CEG" ("ADOSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MUNKALTATO_CEG_KATEGORIAK_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK_UK1" ON "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" ("ADOSZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010088
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010088" ON "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MUNKAVALLALO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."MUNKAVALLALO_UK1" ON "SZABARNA"."MUNKAVALLALO" ("KAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010092
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010092" ON "SZABARNA"."MUNKAVALLALO" ("SZEMELY_SZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010095
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010095" ON "SZABARNA"."MUNKAVALLALO_KATEGORIAK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ONELETRAJZ_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."ONELETRAJZ_UK1" ON "SZABARNA"."ONELETRAJZ" ("SZEMELY_SZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010103
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010103" ON "SZABARNA"."ONELETRAJZ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGISTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."REGISTER_PK" ON "SZABARNA"."REGISTER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010106
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010106" ON "SZABARNA"."SZAKMAI_TAPASZTALAT" ("CV_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAPASZTALAT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."TAPASZTALAT_UK1" ON "SZABARNA"."TAPASZTALAT" ("SZEMELY_SZAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010110
--------------------------------------------------------

  CREATE UNIQUE INDEX "SZABARNA"."SYS_C0010110" ON "SZABARNA"."TAPASZTALAT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ONREGISTER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SZABARNA"."ONREGISTER" 
AFTER INSERT ON REGISTER
BEGIN
    UPDATE REGISTER SET reg_date = CURRENT_DATE;
END;
/
ALTER TRIGGER "SZABARNA"."ONREGISTER" ENABLE;
--------------------------------------------------------
--  Constraints for Table ALLAS_ADATOK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."ALLAS_ADATOK" MODIFY ("TIPUS" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ALLAS_ADATOK" MODIFY ("LEIRAS" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ALLAS_ADATOK" MODIFY ("MUSZAK" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ALLAS_ADATOK" MODIFY ("HELYSZIN" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ALLAS_ADATOK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ALLAS_ADATOK" ADD CONSTRAINT "ALLAS_ADATOK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ALLAS_LEHETOSEG
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."ALLAS_LEHETOSEG" ADD CONSTRAINT "ALLAS_LEHETOSEG_UK1" UNIQUE ("MK_ADOSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."ALLAS_LEHETOSEG" ADD CONSTRAINT "ALLAS_LEHETOSEG_UK2" UNIQUE ("MC_ADOSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."ALLAS_LEHETOSEG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."ALLAS_LEHETOSEG" MODIFY ("MC_ADOSZAM" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ALLAS_LEHETOSEG" MODIFY ("MK_ADOSZAM" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ALLAS_LEHETOSEG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ISKOLAI_VEGZETTSEGEK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."ISKOLAI_VEGZETTSEGEK" ADD PRIMARY KEY ("CV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."ISKOLAI_VEGZETTSEGEK" MODIFY ("ISKOLAI_VEGZETTSEG" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ISKOLAI_VEGZETTSEGEK" MODIFY ("CV_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KOZVETITESEK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."KOZVETITESEK" ADD PRIMARY KEY ("ADOSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."KOZVETITESEK" MODIFY ("KOZ_KOD" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."KOZVETITESEK" MODIFY ("SZEMELY_SZAM" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."KOZVETITESEK" MODIFY ("ADOSZAM" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."KOZVETITESEK" ADD CONSTRAINT "KOZVETITESEK_UK1" UNIQUE ("SZEMELY_SZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KOZVETITO
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."KOZVETITO" ADD PRIMARY KEY ("ADOSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."KOZVETITO" MODIFY ("HELYSZIN" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."KOZVETITO" MODIFY ("MEGNEVEZES" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."KOZVETITO" MODIFY ("ADOSZAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUNKALTATO_CEG
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG" ADD PRIMARY KEY ("ADOSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG" MODIFY ("TELEPHELY" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG" MODIFY ("ADOSZAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUNKALTATO_CEG_KATEGORIAK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" MODIFY ("MEGNEVEZES" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" MODIFY ("ADOSZAM" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" ADD CONSTRAINT "MUNKALTATO_CEG_KATEGORIAK_UK1" UNIQUE ("ADOSZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MUNKAVALLALO
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."MUNKAVALLALO" ADD CONSTRAINT "MUNKAVALLALO_UK1" UNIQUE ("KAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."MUNKAVALLALO" ADD PRIMARY KEY ("SZEMELY_SZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."MUNKAVALLALO" MODIFY ("KAT_ID" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."MUNKAVALLALO" MODIFY ("NEV" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."MUNKAVALLALO" MODIFY ("SZEMELY_SZAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MUNKAVALLALO_KATEGORIAK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."MUNKAVALLALO_KATEGORIAK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."MUNKAVALLALO_KATEGORIAK" MODIFY ("MEGNEVEZES" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."MUNKAVALLALO_KATEGORIAK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ONELETRAJZ
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."ONELETRAJZ" ADD CONSTRAINT "ONELETRAJZ_UK1" UNIQUE ("SZEMELY_SZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."ONELETRAJZ" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."ONELETRAJZ" MODIFY ("SZEMELY_SZAM" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ONELETRAJZ" MODIFY ("REFERENCIA" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."ONELETRAJZ" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTER
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."REGISTER" ADD CONSTRAINT "REGISTER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."REGISTER" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SZAKMAI_TAPASZTALAT
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."SZAKMAI_TAPASZTALAT" ADD PRIMARY KEY ("CV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."SZAKMAI_TAPASZTALAT" MODIFY ("SZAKMAI_TAPASZTALAT" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."SZAKMAI_TAPASZTALAT" MODIFY ("CV_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAPASZTALAT
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."TAPASZTALAT" ADD CONSTRAINT "TAPASZTALAT_UK1" UNIQUE ("SZEMELY_SZAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."TAPASZTALAT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SZABARNA"."TAPASZTALAT" MODIFY ("MEGNEVEZES" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."TAPASZTALAT" MODIFY ("SZEMELY_SZAM" NOT NULL ENABLE);
  ALTER TABLE "SZABARNA"."TAPASZTALAT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALLAS_LEHETOSEG
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."ALLAS_LEHETOSEG" ADD CONSTRAINT "ALLAS_LEHETOSEG_FK1" FOREIGN KEY ("MC_ADOSZAM")
	  REFERENCES "SZABARNA"."KOZVETITO" ("ADOSZAM") ENABLE;
  ALTER TABLE "SZABARNA"."ALLAS_LEHETOSEG" ADD CONSTRAINT "MKCONST1" FOREIGN KEY ("MK_ADOSZAM")
	  REFERENCES "SZABARNA"."MUNKALTATO_CEG" ("ADOSZAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ISKOLAI_VEGZETTSEGEK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."ISKOLAI_VEGZETTSEGEK" ADD CONSTRAINT "ISKOLAI_VEGZETTSEGEK_FK1" FOREIGN KEY ("CV_ID")
	  REFERENCES "SZABARNA"."ONELETRAJZ" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KOZVETITESEK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."KOZVETITESEK" ADD CONSTRAINT "KOZVETITESEK_FK1" FOREIGN KEY ("SZEMELY_SZAM")
	  REFERENCES "SZABARNA"."MUNKAVALLALO" ("SZEMELY_SZAM") ENABLE;
  ALTER TABLE "SZABARNA"."KOZVETITESEK" ADD CONSTRAINT "KOZVETITESEK_FK2" FOREIGN KEY ("ADOSZAM")
	  REFERENCES "SZABARNA"."KOZVETITO" ("ADOSZAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KOZVETITO
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."KOZVETITO" ADD CONSTRAINT "KOZVETITO_CEG_FK1" FOREIGN KEY ("ADOSZAM")
	  REFERENCES "SZABARNA"."KOZVETITESEK" ("ADOSZAM") ENABLE;
  ALTER TABLE "SZABARNA"."KOZVETITO" ADD CONSTRAINT "KOZVETITO_CEG_FK2" FOREIGN KEY ("ADOSZAM")
	  REFERENCES "SZABARNA"."ALLAS_LEHETOSEG" ("MC_ADOSZAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNKALTATO_CEG
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG" ADD CONSTRAINT "MUNKALTATO_CEG_FK1" FOREIGN KEY ("ADOSZAM")
	  REFERENCES "SZABARNA"."ALLAS_LEHETOSEG" ("MK_ADOSZAM") ENABLE;
  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG" ADD CONSTRAINT "MUNKALTATO_CEG_FK2" FOREIGN KEY ("ADOSZAM")
	  REFERENCES "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" ("ADOSZAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNKALTATO_CEG_KATEGORIAK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."MUNKALTATO_CEG_KATEGORIAK" ADD CONSTRAINT "MUNKALTATO_CEG_KATEGORIAK_FK1" FOREIGN KEY ("ADOSZAM")
	  REFERENCES "SZABARNA"."MUNKALTATO_CEG" ("ADOSZAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNKAVALLALO
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."MUNKAVALLALO" ADD CONSTRAINT "MUNKAVALLALO_FK1" FOREIGN KEY ("KAT_ID")
	  REFERENCES "SZABARNA"."MUNKAVALLALO_KATEGORIAK" ("ID") ENABLE;
  ALTER TABLE "SZABARNA"."MUNKAVALLALO" ADD CONSTRAINT "MUNKAVALLALO_FK2" FOREIGN KEY ("SZEMELY_SZAM")
	  REFERENCES "SZABARNA"."TAPASZTALAT" ("SZEMELY_SZAM") ENABLE;
  ALTER TABLE "SZABARNA"."MUNKAVALLALO" ADD CONSTRAINT "MUNKAVALLALO_FK3" FOREIGN KEY ("SZEMELY_SZAM")
	  REFERENCES "SZABARNA"."ONELETRAJZ" ("SZEMELY_SZAM") ENABLE;
  ALTER TABLE "SZABARNA"."MUNKAVALLALO" ADD CONSTRAINT "MUNKAVALLALO_FK4" FOREIGN KEY ("SZEMELY_SZAM")
	  REFERENCES "SZABARNA"."KOZVETITESEK" ("SZEMELY_SZAM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNKAVALLALO_KATEGORIAK
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."MUNKAVALLALO_KATEGORIAK" ADD CONSTRAINT "MUNKAVALLALO_KATEGORIAK_FK1" FOREIGN KEY ("ID")
	  REFERENCES "SZABARNA"."MUNKAVALLALO" ("KAT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ONELETRAJZ
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."ONELETRAJZ" ADD CONSTRAINT "ONELETRAJZ_FK1" FOREIGN KEY ("ID")
	  REFERENCES "SZABARNA"."SZAKMAI_TAPASZTALAT" ("CV_ID") ENABLE;
  ALTER TABLE "SZABARNA"."ONELETRAJZ" ADD CONSTRAINT "ONELETRAJZ_FK2" FOREIGN KEY ("ID")
	  REFERENCES "SZABARNA"."ISKOLAI_VEGZETTSEGEK" ("CV_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZAKMAI_TAPASZTALAT
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."SZAKMAI_TAPASZTALAT" ADD CONSTRAINT "SZAKMAI_TAPASZTALAT_FK1" FOREIGN KEY ("CV_ID")
	  REFERENCES "SZABARNA"."ONELETRAJZ" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAPASZTALAT
--------------------------------------------------------

  ALTER TABLE "SZABARNA"."TAPASZTALAT" ADD CONSTRAINT "TAPASZTALAT_FK1" FOREIGN KEY ("SZEMELY_SZAM")
	  REFERENCES "SZABARNA"."MUNKAVALLALO" ("SZEMELY_SZAM") ENABLE;
